version: '3'
services:
  app_new_php:
    container_name: app_new_php
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - .docker/php/conf.d/:/usr/local/etc/php/conf.d/
    networks:
      - app-network
  app_new_nginx:
    image: nginx:latest
    container_name: app_new_nginx
    volumes:
    - ./:/var/www
    - .docker/nginx/conf.d/:/etc/nginx/conf.d/
    - .docker/nginx/cache/:/etc/nginx/cache/
    ports:
    - "8787:80"
    - "7343:433"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
